server:
  port: ${GATEWAY_PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes

logging:
  level:
    root: INFO
    com.tcon.api_gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO

jwt:
  secret: ${JWT_SECRET:my-super-secret-jwt-key-for-educonnect-platform-minimum-256-bits-required}
  expiration: ${JWT_EXPIRATION_MS:86400000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION_MS:604800000}

resilience4j:
  circuitbreaker:
    instances:

      # ✅ ADD THIS (IMPORTANT)
      support-service-cb:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3


      auth-cb:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

      user-role-cb:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

      assignments-cb:
        slidingWindowSize: 10
        failureRateThreshold: 50

      questions-cb:
        slidingWindowSize: 10
        failureRateThreshold: 50

      submissions-cb:
        slidingWindowSize: 10
        failureRateThreshold: 50

      material-cb:
        slidingWindowSize: 10
        failureRateThreshold: 50

      recordings-cb:
        slidingWindowSize: 10
        failureRateThreshold: 50

      courses-cb:
        slidingWindowSize: 10
        failureRateThreshold: 50

        timelimiter:
          instances:
            support-service-cb:
              timeoutDuration: 5s

gateway:
  rate-limiter:
    default:
      replenishRate: 10
      burstCapacity: 20