
  server:
    port: 8080

  spring:
    application:
      name: api-gateway

    cloud:
      gateway:
        discovery:
          locator:
            enabled: false

        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

  eureka:
    client:
      enabled: true

  jwt:
    secret: my-super-secret-jwt-key-for-educonnect-platform-minimum-256-bits-required
    expiration: 86400000

  logging:
    level:
      root: INFO
      com.tcon.api_gateway: DEBUG
      org.springframework.cloud.loadbalancer: OFF
      com.netflix.discovery: OFF